name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        FACEBOOK_CLIENT_ID: ${{ FACEBOOK_CLIENT_ID }}
        FACEBOOK_CLIENT_SECRET: ${{ FACEBOOK_CLIENT_SECRET }}
        MAIL_HOST: ${{ MAIL_HOST }}
        MAIL_USERNAME: ${{ MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ MAIL_PASSWORD }}
        MAIL_PORT: ${{ MAIL_PORT }}
        LOGS_PATH: ${{ LOGS_PATH }}  

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: ./mvnw -B package --file pom.xml
